# Tests for the batch of windows. The fixed-seed fixture is a hardcoded
# literal, generated by the reference implementation and checked by hand
# against the stream it was drawn from. Failure messages are teaching content
# (CLAUDE.md).

import numpy as np
from submission import get_batch

# A stream whose ids are their own positions, so a window that starts at 24
# reads 24, 25, 26, 27 and any mistake in the arithmetic is visible.
STREAM = np.arange(100, dtype=np.int64)


def test_shapes_and_dtype():
    """get_batch: two (B, T) int64 arrays, batch first and time second"""
    x, y = get_batch(STREAM, 4, 3, np.random.default_rng(0))
    assert x.shape == (3, 4) and y.shape == (3, 4), (
        f"asked for 3 windows of 4, so both arrays must be (3, 4): batch "
        f"first, time second. Got x{x.shape} and y{y.shape}. If yours are "
        "(4, 3) the two axes are swapped, which every later chapter would "
        "read as 4 windows of 3."
    )
    assert x.dtype == np.int64 and y.dtype == np.int64, (
        f"both arrays must stay int64 (got {x.dtype} and {y.dtype}). These "
        "are ids, and an id indexes a row of a table."
    )


def test_targets_are_the_window_shifted():
    """get_batch: y is x shifted one character left"""
    x, y = get_batch(STREAM, 6, 5, np.random.default_rng(1))
    assert (y[:, :-1] == x[:, 1:]).all(), (
        "every target except the last in a row is the next character of the "
        "same window, so y[:, :-1] must equal x[:, 1:]. In the first row you "
        f"gave x = {x[0].tolist()} and y = {y[0].tolist()}. Take y from the "
        "stream starting one character later than x, rather than shifting x "
        "itself."
    )
    assert (y == x + 1).all(), (
        f"in this stream every id is its own position, so y is x plus 1 "
        f"everywhere. Row 0: x = {x[0].tolist()}, y = {y[0].tolist()}. The "
        "last target is the character just past the window, which is why y "
        "must be sliced from the stream and not built from x alone."
    )


def test_rows_are_runs_of_the_stream():
    """get_batch: a window is consecutive characters, not a random selection"""
    x, _ = get_batch(STREAM, 8, 4, np.random.default_rng(2))
    for b, row in enumerate(x.tolist()):
        assert row == list(range(row[0], row[0] + 8)), (
            f"row {b} is {row}, which is not 8 consecutive ids. A window is a "
            "slice of the stream, ids[s : s + block_size]: one starting point "
            "per row, and the characters that follow it in the text."
        )


def test_the_generator_is_the_callers():
    """get_batch: the same seed gives the same batch"""
    a = get_batch(STREAM, 5, 4, np.random.default_rng(11))
    b = get_batch(STREAM, 5, 4, np.random.default_rng(11))
    assert (a[0] == b[0]).all() and (a[1] == b[1]).all(), (
        "two generators made from the same seed must give the same batch, and "
        f"yours gave {a[0][0].tolist()} then {b[0][0].tolist()}. Draw only "
        "from the rng you were passed: np.random.seed, np.random.randint or a "
        "generator built inside the function all break this, and with it every "
        "number in the course that a reader is meant to reproduce."
    )
    c = get_batch(STREAM, 5, 4, np.random.default_rng(12))
    assert not (a[0] == c[0]).all(), (
        "a different seed must give different windows; seeds 11 and 12 gave "
        "the same batch. That happens when the starts do not come from the "
        "generator at all (a fixed start, or one that walks the stream in "
        "order)."
    )


def test_exact_windows_for_a_fixed_seed():
    """get_batch: seed 2 draws these three windows, in this order"""
    x, y = get_batch(STREAM, 4, 3, np.random.default_rng(2))
    want_x = [[79, 80, 81, 82], [24, 25, 26, 27], [10, 11, 12, 13]]
    want_y = [[80, 81, 82, 83], [25, 26, 27, 28], [11, 12, 13, 14]]
    assert x.tolist() == want_x and y.tolist() == want_y, (
        f"seed 2 on this stream must give x = {want_x} and y = {want_y}, and "
        f"gave x = {x.tolist()} and y = {y.tolist()}. If your windows are "
        "right but different, the draw is not the one the contract states: "
        "one call to rng.integers(0, len(ids) - block_size - 1, "
        "size=batch_size), whose numbers arrive in that order. A loop that "
        "draws one start per row is just as random and asks the generator for "
        "its numbers differently, so the chapter's batch would not come back."
    )


def test_never_reads_past_the_end():
    """get_batch: a window plus its last target stay inside the stream"""
    short = np.arange(12, dtype=np.int64)
    rng = np.random.default_rng(99)
    for _ in range(50):
        x, y = get_batch(short, 8, 4, rng)
        assert x.max() < len(short) and y.max() < len(short), (
            f"an id of {max(int(x.max()), int(y.max()))} came out of a stream "
            f"of {len(short)} ids, so a slice ran off the end and NumPy "
            "returned a short row (or the row wrapped around). The last "
            "target sits one past the window, so the largest start the draw "
            "may return is len(ids) - block_size - 2."
        )
        assert x.shape == (4, 8) and y.shape == (4, 8), (
            f"the rows must all be full: got x{x.shape}, y{y.shape}. A slice "
            "that runs past the end of an array comes back short rather than "
            "raising, and np.stack then refuses to build the batch."
        )


def test_window_of_one_is_a_pair():
    """get_batch: T = 1 is chapter 1's pair, one character in, one out"""
    x, y = get_batch(STREAM, 1, 6, np.random.default_rng(5))
    assert x.shape == (6, 1) and y.shape == (6, 1), (
        f"a window of 1 is still a window: (6, 1), not (6,). Got x{x.shape} "
        f"and y{y.shape}. The time axis exists even when it holds one "
        "position, because everything downstream indexes [b, t]."
    )
    assert (y == x + 1).all(), (
        f"with block_size 1 each row is one character and its successor, "
        f"which is exactly the pair chapter 1 counted. Got x = "
        f"{x.ravel().tolist()} and y = {y.ravel().tolist()}."
    )
