# Tests for the softmax exercise. Fixture values are hardcoded literals,
# generated by the reference implementation and checked by hand against the
# definition. Failure messages are teaching content (CLAUDE.md).

import numpy as np
from submission import softmax


def test_uniform_scores():
    """softmax: equal scores mean an even split"""
    got = softmax(np.array([0.0, 0.0, 0.0, 0.0]))
    assert np.allclose(got, [0.25, 0.25, 0.25, 0.25], atol=1e-12), (
        f"softmax([0, 0, 0, 0]) should be [0.25, 0.25, 0.25, 0.25]: four "
        f"equal scores split the probability evenly. Got {np.round(got, 6)}. "
        "If yours does not even return numbers here, check that you divide "
        "by the row's sum, not by the row."
    )


def test_known_row():
    """softmax: one row of scores, checked to ten decimals"""
    got = softmax(np.array([2.0, 0.0, -2.0, 1.0]))
    want = np.array([0.6572330228, 0.0889468173, 0.0120376427, 0.2417825172])
    assert isinstance(got, np.ndarray), (
        f"softmax must return a NumPy array, and yours returned a "
        f"{type(got).__name__}. Do the arithmetic on the array itself, np.exp "
        "and .sum(axis=-1, keepdims=True), rather than on a list of its numbers."
    )
    assert got.shape == want.shape, (
        f"softmax must keep the shape of its input: gave it (4,), got back "
        f"{got.shape}. The max and the sum both need keepdims=True."
    )
    assert np.allclose(got, want, atol=1e-9), (
        f"softmax([2, 0, -2, 1]) should be {np.round(want, 6)}, got "
        f"{np.round(got, 6)}. Each entry is e to the power of its score, "
        "divided by the total of all four such powers (7.389 + 1.000 + "
        "0.135 + 2.718 = 11.243). If your numbers are negative or above 1, "
        "you divided the raw scores by their sum instead of exponentiating "
        "first."
    )


def test_rows_sum_to_one():
    """softmax: every row of a batch sums to 1, along the last axis"""
    scores = np.array([[[1.0, 2.0, 3.0], [0.0, 0.0, 0.0]],
                       [[-1.0, 1.0, 0.0], [5.0, 5.0, 5.0]]])
    got = softmax(scores)
    assert got.shape == scores.shape, (
        f"softmax on a (2, 2, 3) batch must return (2, 2, 3), got "
        f"{got.shape}. The rows live on the LAST axis; use axis=-1."
    )
    sums = got.sum(axis=-1)
    assert np.allclose(sums, 1.0, atol=1e-12), (
        f"every row must sum to 1; these sum to {np.round(sums.ravel(), 6)}. "
        "If some rows are off, your max or your sum ran over the wrong "
        "axis: both belong on axis=-1 with keepdims=True."
    )
    want_first = np.array([0.0900305732, 0.2447284711, 0.6652409558])
    assert np.allclose(got[0, 0], want_first, atol=1e-9), (
        f"the first row [1, 2, 3] should give {np.round(want_first, 6)}, "
        f"got {np.round(got[0, 0], 6)}. A row's answer must not depend on "
        "any other row in the batch."
    )


def test_huge_scores_stay_finite():
    """softmax: scores of 1000 do not overflow"""
    got = softmax(np.array([1000.0, 1000.0, 999.0]))
    assert np.isfinite(got).all(), (
        "softmax([1000, 1000, 999]) produced inf or nan. e to the power of "
        "1000 overflows float64; subtract the row's own maximum from every "
        "score before exponentiating (it cancels out of the answer, and "
        "keeps every exponent at or below zero)."
    )
    want = np.array([0.4223187983, 0.4223187983, 0.1553624035])
    assert np.allclose(got, want, atol=1e-9), (
        f"expected {np.round(want, 6)}, got {np.round(got, 6)}. The two "
        "scores of 1000 must tie exactly, and 999 sits e times lower."
    )


def test_shift_invariance():
    """softmax: adding a constant to every score changes nothing"""
    row = np.array([2.0, 0.0, -2.0, 1.0])
    assert np.allclose(softmax(row + 100.0), softmax(row), atol=1e-9), (
        "adding 100 to every score changed your answer. It must not: the "
        "factor e^100 multiplies the top and the bottom of every entry and "
        "cancels. If your answer changed, you are normalizing the raw "
        "scores somewhere instead of their exponentials."
    )


def test_bigger_score_bigger_probability():
    """softmax: order in, order out"""
    got = softmax(np.array([3.0, -1.0, 0.5]))
    order = np.argsort(got)
    assert list(order) == [1, 2, 0], (
        f"the scores rank as -1 < 0.5 < 3, so the probabilities must rank "
        f"the same way. Yours rank as positions {list(order)} (smallest "
        "first). A flipped order usually means a minus sign on the scores "
        "or a division the wrong way up."
    )
